remove duplicated entry and added missing translations to pt_BR.json
Laravel-Lang/lang pull request #1375
Opened 2020-09-30 07:07 UTC by mvalim

2020-09-30 07:51 UTC, mvalim commented
Please ignore the comment about removing a duplicated entry, at first I did not noticed the casing difference from the word "Your"

2020-09-30 15:55 UTC, luisprmat commented
At the moment it does not seem correct to delete translation strings. It could be lost support for those who use old versions of Laravel or other projects like `laravel/ui`

2020-09-30 16:28 UTC, mvalim commented
I agree with you, if you're addressing my first commit, I noticed my mistake and returned the translation string that I removed, and them I proceed to copy the missing translation strings from en.json and translating them.

2020-09-30 20:44 UTC, jorgercosta commented on json/pt_BR.json
> +    "Add Team Member": "Adicionar membro do time",
Should it be "Adicionar membro ao time",

2020-09-30 20:46 UTC, jorgercosta commented on json/pt_BR.json
> +    "Are you sure you would like to delete this API token?": "Tem certeza de que deseja excluir este Token da API?",
Uppercase Token vs token

2020-09-30 20:47 UTC, jorgercosta commented on json/pt_BR.json
> +    "Create a new team to collaborate with others on projects.": "Crie um time para colaborar em outros projetos.",
I believe it should be "Crie um time para colaborar com outros  em projetos.",

2020-09-30 20:49 UTC, jorgercosta commented on json/pt_BR.json
> +    "Ensure your account is using a long, random password to stay secure.": "Garanta que sua conta esteja usando uma senha longa, e não previsível para se manter seguro.",
Consider translating random as "aleatória"

2020-09-30 20:51 UTC, jorgercosta commented on json/pt_BR.json
> +    "If necessary, you may logout of all of your other browser sessions across all of your devices. If you feel your account has been compromised, you should also update your password.": "Se necessár
Consider translating "other browser sessions" I suggest "outras sessões de navegador"

2020-09-30 20:52 UTC, jorgercosta commented on json/pt_BR.json
> +    "Logout Other Browser Sessions": "Desconectar outras sessões de navegadores",
Consider "Desconectar outras sessões de navegador"

2020-09-30 21:00 UTC, jorgercosta commented on json/pt_BR.json
> +    "to": "para",
Please review the pagination context I believe I should be "até" as in "Mostrando 4 até 10 de 200 resultados"

Here's the original code [(https://github.com/laravel/framework/blob/e63abd8d372f9bad3ca95570cb7e603f3ef28bdc/src/Illuminate/Pagination/resources/views/tailwind.blade.php]((https://github.com/laravel/framework/blob/e63abd8d372f9bad3ca95570cb7e603f3ef28bdc/src/Illuminate/Pagination/resources/views/tailwind.blade.php)

2020-09-30 21:04 UTC, jorgercosta commented on json/pt_BR.json
> +    "Regenerate Recovery Codes": "Gerar novamente os códigos de verificação",
Please consider "Gerar novamente os códigos de recuperação"

2020-09-30 21:05 UTC, jorgercosta commented on json/pt_BR.json
> +    "Please copy your new API token. For your security, it won't be shown again.": "Por favor copie seu novo Token da API. Para sua segurança, ele não será mostrado novamente.",
Please consider lowercase "token da API"

2020-09-30 21:09 UTC, jorgercosta commented on json/pt_BR.json
> +    "API Token Permissions": "Permissões do token da API",
Please consider uppercase Token

2020-09-30 21:14 UTC, jorgercosta commented on json/pt_BR.json
> +    "You may not delete your personal team.": "Você não pode deletar o seu time pessoal.",
Please consider replacing "deletar" with "excluir" to make it more coherent.

2020-09-30 21:16 UTC, jorgercosta commented on json/pt_BR.json
>      "Forgot Your Password?": "Esqueceu a senha?",
Please consider adding the uppercase "Senha"

2020-09-30 21:24 UTC, jorgercosta commented on json/pt_BR.json
> +    "Recovery Code": "Código de recuperação",
Please consider "Código de Recuperação"

2020-09-30 21:24 UTC, jorgercosta commented on json/pt_BR.json
> +    "Profile Information": "Informações do perfil",
Please consider "Informações do Perfil"

2020-09-30 21:25 UTC, jorgercosta commented on json/pt_BR.json
> +    "Remove Team Member": "Remover membro do time",
Please consider "Remover Membro do Time"

2020-09-30 21:26 UTC, jorgercosta commented on json/pt_BR.json
> +    "Show Recovery Codes": "Mostrar códigos de recuperação",
Please consider "Mostrar Códigos de Recuperação"

2020-09-30 21:29 UTC, jorgercosta commented on json/pt_BR.json
> +    "Leave Team": "Sair do time",
Please consider "Sair do Time"

2020-09-30 21:30 UTC, jorgercosta commented on json/pt_BR.json
> +    "Switch Teams": "Mudar de time",
Please consider "Mudar de Time"

2020-09-30 21:31 UTC, jorgercosta commented on json/pt_BR.json
> +    "Team Details": "Detalhes do time",
Please consider "Detalhes do Time"

2020-09-30 21:32 UTC, jorgercosta commented on json/pt_BR.json
> +    "Team Members": "Membros do time",
Please consider "Detalhes do Time"

2020-09-30 21:33 UTC, jorgercosta commented on json/pt_BR.json
> +    "Team Name": "Nome do time",
Please consider "Nome do Time"

2020-09-30 21:33 UTC, jorgercosta commented on json/pt_BR.json
> +    "Team Owner": "Dono do time",
Please consider "Dono do Time"

2020-09-30 21:33 UTC, jorgercosta commented on json/pt_BR.json
> +    "Team Settings": "Configurações do time",
Please consider "Configurações do Time"

2020-09-30 21:41 UTC, jorgercosta requested changes
Great work,  please reviewer my  comments
Most are corrections that I considered more appropriate, especially related to uppercasing/lowercasing  words 

Please correct the missing translations.

All in all great work!

2020-09-30 22:42 UTC, mvalim commented
@jorgercosta I've applied the corrections suggested in my last commit, please confirm if it's ok now. Thanks!

2020-09-30 22:49 UTC, jorgercosta approved these changes
Look's fine, thank's

2020-10-01 12:38 UTC, merged

2020-10-01 12:38 UTC, caouecs commented
Obrigado