docs: translate validate inline into malay lang
Laravel-Lang/lang pull request #1387
Opened 2020-10-03 09:53 UTC by kamaroolkarim

2020-10-03 14:38 UTC, caouecs requested changes
Thank you, just some typos

2020-10-03 14:38 UTC, caouecs commented on src/ms/validation-inline.php
> +    'dimensions'           => 'Dimensi imej tidak sah',
Respect the sort please

2020-10-03 14:38 UTC, caouecs commented on src/ms/validation-inline.php
> +    'starts_with'          => 'Nilai mesti bermula dengan salah satu dari: :values',
A "." at the end

2020-10-03 14:38 UTC, caouecs commented on src/ms/validation-inline.php
> +     */
No space here

2020-10-03 15:31 UTC, andrey-helldar commented on src/ms/validation-inline.php
> +    'active_url'           => 'URL ini adalah tidak sah',
A "." at the end.

2020-10-03 15:31 UTC, andrey-helldar commented on src/ms/validation-inline.php
> +    'alpha'                => 'Ruangan ini hanya boleh mengandungi hurug',
A "." at the end.

2020-10-03 15:31 UTC, andrey-helldar commented on src/ms/validation-inline.php
> +    'dimensions'           => 'Dimensi imej tidak sah',
A "." at the end.

2020-10-03 15:31 UTC, andrey-helldar commented on src/ms/validation-inline.php
> +     */
No space here.

2020-10-04 12:14 UTC, kamaroolkarim commented
@caouecs @andrey-helldar currently reviewing the comments. will patch it tomorrow.

2020-10-05 05:13 UTC, andrey-helldar approved these changes

2020-10-05 12:30 UTC, merged

2020-10-06 01:43 UTC, kamaroolkarim commented
most welcome @caouecs