Update fr.json
Laravel-Lang/lang pull request #1411
Opened 2020-10-09 00:34 UTC by alancolant

add 3 translations

2020-10-09 05:53 UTC, caouecs requested changes
Merci mais il ne faut pas ajouter des tags non officiels

2020-10-09 05:53 UTC, caouecs commented on src/fr/validation-inline.php
> +        'current_password'      => 'mot de passe actuel',
Pourquoi ajouter ce tag ? Il ne fait pas partie de la liste officielle

2020-10-09 05:53 UTC, caouecs commented on src/fr/validation.php
> +        'current_password'      => 'mot de passe actuel',
Pourquoi ajouter ce tag ? Il ne fait pas partie de la liste officielle

2020-10-09 13:35 UTC, alancolant commented on src/fr/validation-inline.php
> +        'current_password'      => 'mot de passe actuel',
Ah juste c'était juste une traduction manquante pour jetstream, je n'ai pas fait attention au fait qu'il ne faisait pas parti des tags officiels

2020-10-10 13:32 UTC, merged

2020-10-10 13:33 UTC, caouecs commented
merci