Added 29 missing translations from the todo list
Laravel-Lang/lang pull request #1412
Opened 2020-10-09 10:25 UTC by ChristofK

and changed the translation of the term "Whoops, something went wrong on our servers". The reference to the server was missing in the German translation.

2020-10-09 11:55 UTC, olsza commented
Hay @ChristofK did you make a typo in "Administrator" translation?
Isn't "Administrator" the same in German as in English? As it is, see this information https://github.com/Laravel-Lang/lang/blob/master/CONTRIBUTING.md#what-should-i-do-if-there-is-a-tag-whose-translation-is-the-same-as-in-english

2020-10-09 12:30 UTC, caouecs requested changes
Danke, just two tags in exclude/de.php

2020-10-09 12:30 UTC, caouecs commented on json/de.json
> +    "Administrator": "Administator",
in exclude/de.php

2020-10-09 12:30 UTC, caouecs commented on json/de.json
> +    "Code": "Code",
in exclude/de.php

2020-10-09 12:56 UTC, ChristofK commented
> Hay @ChristofK did you make a typo in "Administrator" translation?
> Isn't "Administrator" the same in German as in English? As it is, see this information https://github.com/Laravel-Lang/lang/blob/master/CONTRIBUTING.md#what-should-i-do-if-there-is-a-tag-whose-translation-is-the-same-as-in-english
Yes, you are right. It wa just a typo. I removed all strings that do not need to be translated and put them in the exclusion list.

2020-10-09 12:57 UTC, ChristofK commented on json/de.json
> +    "Code": "Code",
done

2020-10-09 12:57 UTC, ChristofK commented on json/de.json
> +    "Administrator": "Administator",
done

2020-10-09 12:59 UTC, olsza commented on json/de.json
> -    "Administrator": "Administator",
as for me, you deleted unnecessarily ... you should leave them in their original form ... words that are in "exclusions" files, they only exclude information in the ToDo.md report

2020-10-09 12:59 UTC, olsza commented on json/de.json
> -    "Code": "Code",
as above

2020-10-09 12:59 UTC, olsza commented on json/de.json
> -    "Dashboard": "Dashboard",
as above

2020-10-09 12:59 UTC, olsza commented on json/de.json
> -    "Name": "Name",
as above

2020-10-09 13:31 UTC, ChristofK commented
I hope everything is right now.

2020-10-10 13:37 UTC, caouecs requested changes
Danke but you have a problem on double "

2020-10-10 13:37 UTC, caouecs commented on json/de.json
> +    "Go to page :page": "Gehe zur Seite :page"",
Error here with two "

2020-10-10 15:37 UTC, ChristofK commented on json/de.json
> +    "Go to page :page": "Gehe zur Seite :page"",
corrected

2020-10-11 08:44 UTC, merged

2020-10-11 08:44 UTC, caouecs commented
Danke