[vi] update json and validation-inline
Laravel-Lang/lang pull request #1433
Opened 2020-10-27 15:16 UTC by l3lackheart

2020-10-28 10:03 UTC, caouecs requested changes
Hello,
thank you, but just a typo on "and"

2020-10-28 10:03 UTC, caouecs commented on src/vi/validation-inline.php
> +    'digits_between' => 'Độ dài của trường này phải nằm trong khoảng :min and :max chữ số.',
and

2020-10-29 06:52 UTC, l3lackheart commented on src/vi/validation-inline.php
> +    'digits_between' => 'Độ dài của trường này phải nằm trong khoảng :min and :max chữ số.',
fixed! tks

2020-10-29 07:35 UTC, merged

2020-10-29 07:35 UTC, caouecs commented
Thank you