Add exclusions of id lang
Laravel-Lang/lang pull request #1438
Opened 2020-11-06 14:56 UTC by Mammo32

2020-11-06 14:57 UTC, Mammo32 commented
Add exlusions file

2020-11-06 15:00 UTC, Mammo32 commented
#1438

2020-11-06 15:01 UTC, Mammo32 commented
#1438

2020-11-07 12:25 UTC, andrey-helldar requested changes

2020-11-07 12:25 UTC, andrey-helldar commented on composer.json
> +    "name": "mammo32_laravel/lang",
Why did you change the application namespace?

2020-11-07 12:25 UTC, andrey-helldar commented on README.md
> -| Laravel 6.x                         | `composer require laravel-lang/lang:~5.0` |
Why did you remove the list of supported Laravel versions?

2020-11-25 22:38 UTC, andrey-helldar commented on composer.json
> +    "name": "mammo32_laravel/lang",
ping

2020-11-25 22:38 UTC, andrey-helldar commented on README.md
> -| Laravel 6.x                         | `composer require laravel-lang/lang:~5.0` |
ping

2020-11-26 14:09 UTC, closed without merging