[ko] Translate json with some validation
Laravel-Lang/lang pull request #1444
Opened 2020-11-15 17:17 UTC by SilNex

2020-11-15 20:33 UTC, caouecs requested changes
Thank you, just a typo

2020-11-15 20:33 UTC, caouecs commented on src/ko/validation-inline.php
> +    'multiple_of'          => ':attribute 는 :value 의 배수여야 합니다.',
No :attribute here

2020-11-16 08:13 UTC, SilNex commented
fixit !

2020-11-17 20:40 UTC, merged

2020-11-17 20:40 UTC, caouecs commented
Thank you