Update uk.json
Laravel-Lang/lang pull request #1446
Opened 2020-11-18 18:34 UTC by DmitriyKondratyuk

2020-11-18 19:39 UTC, luisprmat requested changes

2020-11-18 19:39 UTC, luisprmat commented on json/uk.json
> +  "Your email address is not verified.": "Ваша електронна адреса не підтверджена."
In this project, we are working with an [**indent size**](https://github.com/Laravel-Lang/lang/blob/master/.editorconfig#L12) of *4 spaces*, you changed this to 2 spaces.

2020-11-19 08:15 UTC, DmitriyKondratyuk reviewed
Changed an indent size of 4 spaces

2020-11-19 20:47 UTC, merged

2020-11-19 20:47 UTC, caouecs commented
Thank you