Added Jetstream profile translation for ja
Laravel-Lang/lang pull request #1461
Opened 2020-11-29 13:18 UTC by jimbaran5601406

2020-11-30 20:30 UTC, caouecs commented
two translations for japanese. Can you @jimbaran5601406  and @yuusakuri work together ? Thank you

2020-12-01 00:44 UTC, jimbaran5601406 commented
No. I added some translations after looking at his translations. Therefore my commit may have a part of his translation.

2020-12-01 03:22 UTC, yuusakuri commented
The translation of @ jimbaran5601406 has modified my translation and added more translations.
So adopt his translation.
My pull request closes.

2020-12-01 03:42 UTC, yuusakuri commented
There was a change request in my pull request.
Would you please change these translations here?
[my pull request](https://github.com/Laravel-Lang/lang/pull/1460)

2020-12-01 04:08 UTC, jimbaran5601406 commented
@yuusakuri 
Thank you for teaching.
I just deleted it instead of adding the translation because it's unnecessary.

2020-12-01 05:44 UTC, yuusakuri commented
@jimbaran5601406 
I'm sorry, my pull request has two commits since the first commit.
So please correct the translation by referring to the commit below.

[commit 2](https://github.com/Laravel-Lang/lang/pull/1460/commits/46f0bef6c3fd9b95dda19cfc8ba096ac9d4bceb6)
[commit 3](https://github.com/Laravel-Lang/lang/pull/1460/commits/05fd57023bd3ada345d7ba72f7a45a40efd173ef)

2020-12-01 06:58 UTC, caouecs commented
> @yuusakuri
> Thank you for teaching.
> I just deleted it instead of adding the translation because it's unnecessary.

if you delete translations, it will be replaced by nothing on your website, so you can see doc for exclude translations : https://github.com/Laravel-Lang/lang/blob/master/CONTRIBUTING.md#what-should-i-do-if-there-is-a-tag-whose-translation-is-the-same-as-in-english

2020-12-01 08:36 UTC, jimbaran5601406 commented
@caouecs 
I'm sorry for misunderstanding.
I excluded the phrase "All rights reserved." and modified some translations by the yuusakuri's comment in the last commit.
Thank you for reviewing.

2020-12-01 12:50 UTC, caouecs requested changes
Thank you but some fixes to do

2020-12-01 12:50 UTC, caouecs commented on json/ja.json
> +    "Create": "",
Need translation or in exclude file

2020-12-01 12:50 UTC, caouecs commented on json/ja.json
> +    "Created.": "",
Need translation or in exclude file

2020-12-01 12:50 UTC, caouecs commented on json/ja.json
> +    "Manage API Tokens": "",
Need translation or in exclude file

2020-12-01 12:50 UTC, caouecs commented on json/ja.json
> +    "Permissions": "",
Need translation or in exclude file

2020-12-01 12:50 UTC, caouecs commented on json/ja.json
> +    "Remember me": "ログイン状態を保持する",
We need "Remember Me" and "Remember me"

2020-12-02 00:30 UTC, jimbaran5601406 commented
@caouecs 
I fixed some and added more translations for ja.
Sorry for many times.

2020-12-02 06:49 UTC, merged

2020-12-02 06:49 UTC, caouecs commented
Thank you