[ru] Fix "Nevermind" incorrect translation
Laravel-Lang/lang pull request #1475
Opened 2020-12-14 22:45 UTC by karvaka

2020-12-15 06:53 UTC, andrey-helldar commented
"Nevermind" переводится как "Никогда".
"Не важно" - "Not important".

2020-12-15 13:45 UTC, karvaka commented
@andrey-helldar "Никогда" переводится как "Never", "Nevermind" переводится как "Не бери в голову", "Не обращай внимания".
Вообще, я не вижу проблемы в точности перевода, она в контексте использования. А именно в переводе кнопок "Nevermind" и "Delete" диалоговых окон пакета Jetstream на "Никогда" и "Удалить". Вас не сбивает это с толку?

--
Sorry, there is no reason to translate this

2020-12-15 15:04 UTC, andrey-helldar commented
Согласен. В рамках контекста эта кнопка, скорее, должна называться "Отмена" либо "Не требуется". Хотя, в половине окон, применимо именно "Не требуется".

Лично для меня "ничего", "не обращай внимания", "не важно" будет вводить в заблуждение.

Например, форма подтверждения пароля:

> For your security, please confirm your password to continue.
>
> Confirm / Nevermind
>
> Для продолжения подтвердите пароль для Вашей безопасности.
> Подтвердить / Не требуется

Данный контекст выдерживают и другие диалоговые окна. В данном случае вариант "Не требуется" будет наиболее оптимальным в контексте.

2020-12-15 15:05 UTC, andrey-helldar requested changes
Замените "Не важно" на "Не требуется".
Такой перевод будет ближе к контексту с учётом того, что файлы перевода используются не только в рамках jetstream.

2020-12-15 18:19 UTC, karvaka commented
Done

2020-12-15 18:19 UTC, andrey-helldar approved these changes

2020-12-15 18:19 UTC, andrey-helldar commented
@caouecs, problem solved :)

2020-12-15 18:22 UTC, andrey-helldar commented
@karvaka, позвольте узнать, каким образом обновляете файлы в проекте?

2020-12-15 18:37 UTC, karvaka commented
@andrey-helldar редактирую файлы через гитхабовский редактор, вопрос ведь в этом?

2020-12-15 18:38 UTC, andrey-helldar commented
@karvaka, не совсем. Вот у Вас есть проект на Laravel/Lumen - в нём как поддерживаете актуальность файлов перевода из пакета Laravel-Lang? Вручную или каким-то менеджером?

2020-12-15 18:47 UTC, karvaka commented
@andrey-helldar понял вопрос. Как правило, вручную выгружаю нужные переводы и также вручную добавляю недостающие фразы при апгрейде мажорной версии фреймворка. Автоматизировать этот подход пока не было нужды.

2020-12-15 21:33 UTC, andrey-helldar commented
@karvaka, фраза "вручную обновляю" уже говорит о необходимости автоматизации 👍 

Заюзай пакет [andrey-helldar/laravel-lang-publisher](https://github.com/andrey-helldar/laravel-lang-publisher).
Он сам всё обновит по ключам, сохранив вручную добавленные.

2020-12-16 00:26 UTC, karvaka commented
@andrey-helldar звучит хорошо, спасибо

2020-12-16 09:29 UTC, caouecs commented
c'est pas faux

2020-12-16 09:29 UTC, merged

2020-12-16 09:29 UTC, caouecs commented
thank you

2020-12-16 09:32 UTC, andrey-helldar commented
> c'est pas faux

Nous avons discuté de la traduction du bouton en fonction du contexte et sommes parvenus à un avis commun.
Je n'ai pas compris le message concernant le mensonge. 🙂

2020-12-16 19:09 UTC, caouecs commented
it's a French joke, you need to know "Kaamelott" ( see https://en.wikipedia.org/wiki/Kaamelott ) :)

2020-12-16 20:27 UTC, andrey-helldar commented
> it's a French joke, you need to know "Kaamelott" ( see https://en.wikipedia.org/wiki/Kaamelott ) :)

I didn't know about that. I'll take a look. Thank you :)