[uk] update 2021
Laravel-Lang/lang pull request #1484
Opened 2021-01-07 13:27 UTC by yarkm13

2021-01-07 14:17 UTC, mostafa2121 commented
On Thu, Jan 7, 2021 at 5:39 PM mostafa sadeghifar <msadeghifar1996@gmail.com>
wrote:

>
>
> On Thu, Jan 7, 2021 at 4:58 PM Yaroslav <notifications@github.com> wrote:
>
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/Laravel-Lang/lang/pull/1484
>> Commit Summary
>>
>>    - Update auth.php
>>    - Update validation.php
>>    - Update validation-inline.php
>>    - Update todo.md
>>    - Update uk.json
>>    - Update todo.md
>>
>> File Changes
>>
>>    - *M* json/uk.json
>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-595c05fc3d53b1d9e7c8d0981241e9ae1b8849298cbea53a55632e320cb10fd0>
>>    (9)
>>    - *M* src/uk/auth.php
>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-4e0ae12531c111c9425ac0c727ccb5feef3c936b405d2822c4a68a001cee67e0>
>>    (1)
>>    - *M* src/uk/validation-inline.php
>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-b748ee9cf25dd63f2324c775e9d9a4db9e887d685fe0738fe1781b65b1a7e277>
>>    (2)
>>    - *M* src/uk/validation.php
>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-486c4aaab1d1e7b543a85e46d1c51e1f447050a8c967b8b3e3ed986759407dc7>
>>    (2)
>>    - *M* todo.md
>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-13432f2375977371d353bba0f2f76fa94385d5c4e247d3083b0b6e83d995be61>
>>    (23)
>>
>> Patch Links:
>>
>>    - https://github.com/Laravel-Lang/lang/pull/1484.patch
>>    - https://github.com/Laravel-Lang/lang/pull/1484.diff
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Laravel-Lang/lang/pull/1484>, or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQWSUQOEWSJCKIEO2C4KX5TSYWZGTANCNFSM4VY7LLQQ>
>> .
>>
>

2021-01-07 15:16 UTC, mostafa2121 commented
On Thu, Jan 7, 2021 at 5:46 PM mostafa sadeghifar <msadeghifar1996@gmail.com>
wrote:

>
>
> On Thu, Jan 7, 2021 at 5:39 PM mostafa sadeghifar <
> msadeghifar1996@gmail.com> wrote:
>
>>
>>
>> On Thu, Jan 7, 2021 at 4:58 PM Yaroslav <notifications@github.com> wrote:
>>
>>> ------------------------------
>>> You can view, comment on, or merge this pull request online at:
>>>
>>>   https://github.com/Laravel-Lang/lang/pull/1484
>>> Commit Summary
>>>
>>>    - Update auth.php
>>>    - Update validation.php
>>>    - Update validation-inline.php
>>>    - Update todo.md
>>>    - Update uk.json
>>>    - Update todo.md
>>>
>>> File Changes
>>>
>>>    - *M* json/uk.json
>>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-595c05fc3d53b1d9e7c8d0981241e9ae1b8849298cbea53a55632e320cb10fd0>
>>>    (9)
>>>    - *M* src/uk/auth.php
>>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-4e0ae12531c111c9425ac0c727ccb5feef3c936b405d2822c4a68a001cee67e0>
>>>    (1)
>>>    - *M* src/uk/validation-inline.php
>>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-b748ee9cf25dd63f2324c775e9d9a4db9e887d685fe0738fe1781b65b1a7e277>
>>>    (2)
>>>    - *M* src/uk/validation.php
>>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-486c4aaab1d1e7b543a85e46d1c51e1f447050a8c967b8b3e3ed986759407dc7>
>>>    (2)
>>>    - *M* todo.md
>>>    <https://github.com/Laravel-Lang/lang/pull/1484/files#diff-13432f2375977371d353bba0f2f76fa94385d5c4e247d3083b0b6e83d995be61>
>>>    (23)
>>>
>>> Patch Links:
>>>
>>>    - https://github.com/Laravel-Lang/lang/pull/1484.patch
>>>    - https://github.com/Laravel-Lang/lang/pull/1484.diff
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/Laravel-Lang/lang/pull/1484>, or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AQWSUQOEWSJCKIEO2C4KX5TSYWZGTANCNFSM4VY7LLQQ>
>>> .
>>>
>>

2021-01-07 16:20 UTC, caouecs requested changes
Thank you, just a problem of typo

2021-01-07 16:20 UTC, caouecs commented on json/uk.json
> +    "Pending Team Invitations": "Запрошення в команди на очікуванні"
Need ,

2021-01-08 10:55 UTC, andrey-helldar requested changes

2021-01-08 10:55 UTC, andrey-helldar commented on json/uk.json
> +    "Pending Team Invitations": "Запрошення в команди на очікуванні"
Додайте кому в кінці рядка. Зараз файл має некоректну структуру.

2021-01-08 11:25 UTC, yarkm13 commented on json/uk.json
> +    "Pending Team Invitations": "Запрошення в команди на очікуванні"
Thanks for reviewing.

2021-01-08 11:41 UTC, andrey-helldar approved these changes

2021-01-08 16:35 UTC, merged

2021-01-08 16:35 UTC, caouecs commented
Thank you