Added Afrikaans language support
Laravel-Lang/lang pull request #1510
Opened 2021-01-15 12:02 UTC by JacquesvanWyk

Hi I was in need for Afrikaans language support for my Laravel application and came across your repo and decided to add the work I have done for Afrikaans language.

2021-01-16 15:04 UTC, caouecs requested changes
Hello,
thank you, can you add validation-inline.php and fix files ?

2021-01-16 15:04 UTC, caouecs commented on src/af/auth.php
> +    'failed' => 'Hierdie verwysings stem nie ooreen met ons rekords nie.',
Need 'password' => 'The provided password is incorrect.',

2021-01-16 15:04 UTC, caouecs commented on src/af/validation.php
> +    'active_url' => 'Die :attribute is nie \'n geldig URL.',
Use " when you have ' in translations

For example here :  'active_url' => "Die :attribute is nie 'n geldig URL.",

2021-02-04 07:59 UTC, caouecs commented
@JacquesvanWyk  ?

2021-02-08 18:59 UTC, andrey-helldar commented
@JacquesvanWyk, ping 🙂

2021-02-09 10:27 UTC, JacquesvanWyk commented
Hey sorry about this been crazy my side. Going to finish this on weekend and send another pull request.

2021-03-11 20:13 UTC, andrey-helldar commented
@JacquesvanWyk, is the situation still crazy?)

2021-03-31 23:20 UTC, andrey-helldar commented
@JacquesvanWyk, ping)

2021-03-31 23:24 UTC, andrey-helldar commented
@caouecs, I propose to accept PR from @JacquesvanWyk. He translated many keys. Yes, not all keys have been translated. The script will generate a todo.md file with missing keys. In any case, it will be better than using Google Translate. What do you say?

2021-03-31 23:29 UTC, JacquesvanWyk commented
Hi
I will have been finishing app that i have used this so was just finishing
that. I will send the updated one in next few days

On Thu, 01 Apr 2021 at 01:24, Andrey Helldar ***@***.***>
wrote:

> @caouecs <https://github.com/caouecs>, I propose to accept PR from
> @JacquesvanWyk <https://github.com/JacquesvanWyk>. He translated many
> keys. Yes, not all keys have been translated. The script will generate a
> todo.md file with missing keys. In any case, it will be better than using
> Google Translate. What do you say?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Laravel-Lang/lang/pull/1510#issuecomment-811528577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC3TZ7UTWNZD4RD2MKRL3PTTGOVK3ANCNFSM4WD6RQHA>
> .
>

2021-04-01 00:39 UTC, JacquesvanWyk commented
Please review

2021-04-01 00:43 UTC, JacquesvanWyk reviewed
Inline Validations done and some other fixes

2021-04-01 06:27 UTC, merged

2021-04-01 06:27 UTC, caouecs commented
thank you