Fixed translations for Serbian Latin.
Laravel-Lang/lang pull request #1598
Opened 2021-04-07 12:26 UTC by stasavs

2021-04-07 17:20 UTC, caouecs requested changes
Hello,
thank you, just a problem in validation-inline.php

2021-04-07 17:20 UTC, caouecs commented on src/sr_Latn/validation-inline.php
> +    'attached'             => 'Ovaj :attribute je već priložen.',
No :attribute here

2021-04-14 17:49 UTC, caouecs commented
with the v9 of this package, the files are been moved

2021-04-14 17:52 UTC, andrey-helldar commented
@stasavs, we have changed the structure of the project.

Files has been moved to a new location:

| old | new |
|:---|:---|
| `src/sr_Latn/auth.php` | `locales/sr_Latn/auth.php`|
| `src/sr_Latn/passwords.php` | `locales/sr_Latn/passwords.php`|
| `src/sr_Latn/validation-inline.php` | `locales/sr_Latn/validation-inline.php`|
| `src/sr_Latn/validation.php` | `locales/sr_Latn/validation.php`|

2021-04-15 06:53 UTC, closed without merging

2021-04-15 09:38 UTC, andrey-helldar commented
@stasavs, we hope you will come back to us 😊
The content of the files in our project remains the same, just the location has changed.