[KO] Translate 'ko.json', 'validation.json', 'validation-inline.json'
Laravel-Lang/lang pull request #1608
Opened 2021-04-12 15:24 UTC by SilNex

2021-04-12 17:36 UTC, caouecs requested changes
Thank you

just a problem in json file

2021-04-12 17:36 UTC, caouecs commented on json/ko.json
> +    "Press / to search": "/을 눌러 검색",
don't change the tag please, and I think \\/ is needed in translation

2021-04-14 17:49 UTC, caouecs commented
with the v9 of this package, the files are been moved

2021-04-14 17:51 UTC, andrey-helldar commented
@SilNex, we have changed the structure of the project.

Files has been moved to a new location:

| old | new |
|:---|:---|
| `json/ko.json` | `locales/ko/ko.json`|
| `src/ko/validation-inline.php` | `locales/ko/validation-inline.php`|
| `src/ko/validation.php` | `locales/ko/validation.php`|

2021-04-14 18:10 UTC, andrey-helldar commented
Run the commands:

```bash
git fetch --all
git checkout -b "patch/d58d7a0" "d58d7a08d64e78a4a3d2f7bfa9eefd58831b19ed"
git switch master
git rebase patch/d58d7a0 master
git push
```

2021-04-15 07:49 UTC, merged

2021-04-15 07:49 UTC, caouecs commented
thank you