[id] Fixed Missed Translations
Laravel-Lang/lang pull request #1621
Opened 2021-04-15 19:54 UTC by itsfaqih

Apparently there're some missed translations and some words that I haven't exclude. So here's the fix, sorry for the inconvenience

2021-04-15 23:40 UTC, andrey-helldar requested changes

2021-04-15 23:40 UTC, andrey-helldar commented on excludes/id.php
> +    'Saint Kitts and Nevis',
The keys to exclude are specified here.

`'Saint Kitts And Nevis' !== 'Saint Kitts and Nevis'`

See: https://github.com/Laravel-Lang/lang/blob/master/source/en.json#L441

2021-04-15 23:40 UTC, andrey-helldar commented on excludes/id.php
> +    'Saint Pierre and Miquelon',
The keys to exclude are specified here.

`'Saint Pierre And Miquelon' !== 'Saint Pierre and Miquelon'`

See: https://github.com/Laravel-Lang/lang/blob/master/source/en.json#L444

2021-04-15 23:40 UTC, andrey-helldar commented on excludes/id.php
> +    'Saint Vincent and Grenadines',
The keys to exclude are specified here.

`'Saint Vincent And Grenadines' !== 'Saint Vincent and Grenadines'`

See: https://github.com/Laravel-Lang/lang/blob/master/source/en.json#L445

2021-04-15 23:40 UTC, andrey-helldar commented on excludes/id.php
> +    'San MarinoID',
Invalid key name

2021-04-15 23:40 UTC, andrey-helldar commented on excludes/id.php
> +    'Sint Maarten(Dutch part)',
Invalid key name.

Correct is `Sint Maarten (Dutch part)`

See: https://github.com/Laravel-Lang/lang/blob/master/source/en.json#L470

2021-04-15 23:40 UTC, andrey-helldar commented on excludes/id.php
> +    'Timor - Leste',
Invalid key name.

Correct is `Timor-Leste`

See: https://github.com/Laravel-Lang/lang/blob/master/source/en.json#L545

2021-04-15 23:44 UTC, andrey-helldar commented
The exception file specifies keys, not values.

2021-04-16 01:39 UTC, itsfaqih commented
Thank you for the review.
Just thought an idea, I think it'd be good if there's a test for checking whether a key is exists or not

2021-04-16 07:07 UTC, andrey-helldar commented
> Thank you for the review.
> Just thought an idea, I think it'd be good if there's a test for checking whether a key is exists or not

We only test the localizations themselves.
Exception files work differently for us - each push to the `master` branch runs a script that checks the keys specified in the files from the `excludes` folder and automatically deletes nonexistent ones.

2021-04-16 16:37 UTC, andrey-helldar approved these changes

2021-04-16 19:04 UTC, merged

2021-04-16 19:04 UTC, caouecs commented
thank you