[pt_BR] Machine translation of missing keys
Laravel-Lang/lang pull request #1647
Opened 2021-04-17 12:22 UTC by andrey-helldar

2021-04-18 17:17 UTC, caouecs commented
@HabiboIV can you help us and review this automatic pull request, please ? thanks by advance

2021-04-19 07:36 UTC, HabiboIV requested changes

2021-04-19 07:36 UTC, HabiboIV commented on locales/pt_BR/validation-inline.php
> +    'attached'             => 'Este campo já está ligado.',
"Este campo já está anexado." sounds better.

2021-04-19 07:36 UTC, HabiboIV commented on locales/pt_BR/validation.php
> +    'attached'             => 'Este :attribute já está ligado.',
"Este :attribute já está anexado." sounds better.

2021-04-19 08:47 UTC, caouecs commented
Ok, I will fix this evening

and for the json file ?

2021-04-19 12:35 UTC, HabiboIV requested changes
more review is needed. from line 255 onwards

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Haiti": "Feira",
"Haiti"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Guyana": "Guianense",
"Guiana"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Guinea-Bissau": "Guine",
"Guiné-Bissau"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Guinea": "Guine",
"Guiné"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Iceland": "Islandês",
"Islândia"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Hong Kong": "reformado",
"Hong Kong"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "India": "Indio",
"India"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Indonesia": "Indonesio",
"Indonesia"

2021-04-19 12:35 UTC, HabiboIV commented on locales/pt_BR/pt_BR.json
> +    "Iran, Islamic Republic Of": "Iraniano",
"Irã"

2021-04-19 13:54 UTC, caouecs commented
Obrigado

Can you do a new pull request starting of this pull request, with your fixes ?

2021-04-19 15:05 UTC, HabiboIV commented
sure. I'll do just that. you will have it in 24h.

On Mon, Apr 19, 2021, 15:55 Fred Delrieu ***@***.***> wrote:

> Obrigado
>
> Can you do a new pull request starting of this pull request, with your
> fixes ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Laravel-Lang/lang/pull/1647#issuecomment-822485613>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKSJKFHSX5YBABFLJWSHSDTJQY3RANCNFSM43DAXYHQ>
> .
>

2021-04-20 10:58 UTC, HabiboIV commented
hello there. i am new to this. 
i have done the corrections. however, i do not have permission to push my changes to "HEAD:patch/2021-04-17/pt_BR"

2021-04-20 11:48 UTC, HabiboIV commented
@andrey-helldar, I have finished reviewing the entirety of json file. should I make a pull to your repository?

2021-04-20 12:17 UTC, HabiboIV commented
@andrey-helldar , I have done a pull request with all my changes to your repository.

2021-04-20 14:01 UTC, andrey-helldar commented
@HabiboIV, thank you. I accepted it.

@caouecs, the changes are in this PR.

@HabiboIV, now everything is fine?

2021-04-20 14:20 UTC, HabiboIV commented
@andrey-helldar , yes, everything is fine now! thank you!

2021-04-20 14:22 UTC, merged

2021-04-20 14:22 UTC, caouecs commented
Obrigado

2021-04-20 14:26 UTC, andrey-helldar commented
@HabiboIV, no you!)

![cover2](https://user-images.githubusercontent.com/10347617/115413005-81b73f00-a1fd-11eb-9ace-16c74e112f5f.jpg)