[bg] Machine translation of missing keys
Laravel-Lang/lang pull request #1669
Opened 2021-04-17 12:24 UTC by andrey-helldar

2021-04-19 20:29 UTC, caouecs commented
@dyanakiev can you help us and review this automatic pull request, please ? thanks by advance

2021-04-23 17:00 UTC, dyanakiev requested changes
Hi @caouecs , there's more to be corrected, should i continue writing correction comments that way?

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "A fresh verification link has been sent to your email address.": "На вашия имейл адрес е изпратена нова връзка за проверка.",
На вашия имейл адрес е изпратена нова връзка за потвърждение.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "A new verification link has been sent to the email address you provided during registration.": "Нова връзка за проверка е изпратена на имейл адреса, посочен от вас при регистрацията.",
Нова връзка за потвърждение е изпратена на имейл адреса, посочен от вас при регистрацията.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Actions": "Валидност",
Действия

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Add": "Добавя",
Добави

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Added.": "Добавя.",
Добавено.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Another user has updated this resource since this page was loaded. Please refresh the page and try again.": "Друг потребител актуализира този ресурс от момента на зареждане на тази страница. Мол
Друг потребител редактира този ресурс от момента на зареждане на тази страница. Моля, презаредете страницата и опитайте отново.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "API Token Permissions": "Разрешения за маркер API",
API Ключ Права

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "API Token": "API token",
API Ключ

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "API Tokens": "API Жетони",
API Ключове

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "API tokens allow third-party services to authenticate with our application on your behalf.": "API символите позволяват на услугите на трети страни да бъдат удостоверени в нашето приложение от ва
API ключовете позволяват на услугите на трети страни да бъдат удостоверени в нашето приложение от ваше име.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Are you sure you want to delete this team? Once a team is deleted, all of its resources and data will be permanently deleted.": "Сигурни ли сте, че искате да изтриете тази команда? След като ком
Сигурни ли сте, че искате да изтриете този екип? След като екипа бъде изтрит, всичките му ресурси и данни ще бъдат изтрити завинаги.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Are you sure you want to run this action?": "Сигурни ли сте, че искате да стартирате това действие?",
Сигурни ли сте, че искате да изпълните това действие?

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Are you sure you would like to delete this API token?": "Сигурни ли сте, че искате да премахнете този API знак?",
Сигурни ли сте, че искате да премахнете този API ключ?

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Are you sure you would like to leave this team?": "Сигурен ли си, че искаш да напуснеш този отбор?",
Сигурен ли си, че искаш да напуснеш този екип?

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Attach": "Прикача",
Прикачи

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Attach & Attach Another": "Прикрепете и прикрепете още един",
Прикачи & Прикачи друг

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Attach :resource": "Приложение :resource",
Прикачи :resource

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Before proceeding, please check your email for a verification link.": "Преди да продължите, моля, проверете електронната си поща за проверка на връзката.",
Преди да продължите, моля, проверете електронната си поща за линк за потвърждение.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "click here to request another": "Кликнете тук, за да поискате още един",
Кликнете тук, за да поискате друг

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Close": "Затварям",
Затвори

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Choose File": "файл",
Изберете файл

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Choose an option": "Избера",
Изберете опция

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Choose": "Избера",
Избери

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Confirm your :amount payment": "Потвърдете плащането си :amount",
Потвърдете плащането си за :amount

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "could not be found.": "не можах да го намеря.",
не може да бъде открит.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Create": "Създавам",
Създай

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Create & Add Another": "Създаване и добавяне на още един",
Създай & Добави друг

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Create :resource": "Създаване на :resource",
Създай :resource

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Create API Token": "Създаване на API знак",
Създаване на API Ключ

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Create New Team": "Създаване На Нова Команда",
Създаване На Нов Екип

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Created.": "Създам.",
Създаден.

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Decrease": "Намалявам",
Намали

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Customize": "Настроя",
Модифицирай

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Delete": "Премахна",
Изтрий

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Delete API Token": "Премахване на маркера API",
Изтриване на API Ключ

2021-04-23 17:00 UTC, dyanakiev commented on locales/bg/bg.json
> +    "Delete File": "Изтрия",
Изтриване на файл

2021-04-23 17:13 UTC, caouecs commented
Hello, I merge and you can do a pull request, ok ?

2021-04-23 17:13 UTC, merged

2021-04-23 18:20 UTC, andrey-helldar commented
@dyanakiev, благодаря ти!

@caouecs, I created a https://github.com/Laravel-Lang/lang/pull/1712 with the above fixes.