[id] Machine translation of missing keys
Laravel-Lang/lang pull request #1689
Opened 2021-04-17 12:25 UTC by andrey-helldar

2021-04-17 19:24 UTC, caouecs commented
@itsfaqih can you check this pull request, please ? thank you

2021-04-18 04:24 UTC, itsfaqih requested changes
I think that's all. Let me know if you need any help related to this translation

2021-04-18 04:24 UTC, itsfaqih commented on locales/id/id.json
> +    "Belgium": "Belgianame",
It's Belgia

2021-04-18 04:24 UTC, itsfaqih commented on locales/id/id.json
>      "Edit": "Edit",
I just realized even though both "edit" and "sunting" are valid in Indonesian, I guess "sunting" is more appropriate here

2021-04-18 04:24 UTC, itsfaqih commented on locales/id/id.json
>      "Editor users have the ability to read, create, and update.": "Editor memiliki kemampuan untuk membaca, membuat, dan memperbarui.",
Change "Editor" to "Penyunting"

2021-04-18 04:24 UTC, itsfaqih commented on locales/id/id.json
> +    "Role": "Tugas",
In this one, "Peran" is more fit than "Tugas". "Tugas" could also mean "Task" while the only translation of "Peran" in English is "Role"

2021-04-18 04:24 UTC, itsfaqih commented on locales/id/id.json
> +    "Saint Kitts And Nevis": "Saint Kitts And Nevis",
"dan" means "and', may I know the reason why changing it back to "and"?

2021-04-18 04:24 UTC, itsfaqih commented on locales/id/id.json
> +    "These people have been invited to your team and have been sent an invitation email. They may join the team by accepting the email invitation.": "Orang-orang ini telah diundang ke tim Anda dan te
Both "tersebut" or "ini" are fine. But, for the "may", in this context, "bisa" or "dapat" (which can also means "could") is more fitting than "mungkin" (which means "probably")

2021-04-20 17:46 UTC, caouecs commented
Ok, I merge and I fix

2021-04-20 17:46 UTC, merged

2021-04-20 17:49 UTC, caouecs commented
done

2021-04-20 21:50 UTC, andrey-helldar commented
I haven't made any changes to this PR yet ><

2021-04-21 06:22 UTC, caouecs commented
I fixed the translations