Replace some wrong character
Laravel-Lang/lang pull request #1779
Opened 2021-06-10 10:40 UTC by Oliverlin67

Replace a part of simple Chinese character to traditional Chinese and remove duplicate content

2021-06-22 21:19 UTC, caouecs requested changes
Thank you but you have deleted a tag

2021-06-22 21:19 UTC, caouecs commented on locales/zh_TW/zh_TW.json
> -    "Antigua and Barbuda": "Antigua and Barbuda",
This tag is needed

2021-06-23 14:38 UTC, Oliverlin67 commented on locales/zh_TW/zh_TW.json
> -    "Antigua and Barbuda": "Antigua and Barbuda",
added

2021-06-23 22:13 UTC, overtrue approved these changes

2021-06-24 15:12 UTC, merged

2021-06-24 15:12 UTC, caouecs commented
thank you