Fix Arabic words gender
Laravel-Lang/lang pull request #1794
Opened 2021-06-30 14:08 UTC by elkebirmed

## Before:
الإسم مطلوب :heavy_check_mark: 
كلمة المرور مطلوب :x: 

## Now:
حقل الإسم مطلوب :heavy_check_mark: 
حقل كلمة المرور مطلوب :heavy_check_mark:

2021-06-30 17:54 UTC, caouecs requested changes
Problem with indentation

2021-06-30 17:54 UTC, caouecs commented on locales/ar/validation.php
> -    'accepted'             => 'يجب قبول :attribute.',
Don't update spaces, please

2021-06-30 18:09 UTC, mohamedsabil83 requested changes
We can approve it after fixing the indentation

2021-06-30 18:55 UTC, mohamedsabil83 approved these changes
@elkebirmed Thank you.
@caouecs You can accept it now.

2021-07-05 10:03 UTC, mohamedsabil83 commented
@elkebirmed Please fix the conflict or you can **Allow edits from maintainers** to this pr.

2021-07-06 09:26 UTC, elkebirmed commented
@mohamedsabil83 @caouecs Conflict resolved :+1:

2021-07-06 10:12 UTC, mohamedsabil83 commented
You can merge it now @caouecs

2021-07-06 13:44 UTC, merged

2021-07-06 13:44 UTC, caouecs commented
Thank you

2021-07-06 14:33 UTC, elkebirmed commented
@caouecs You are welcome