[ca] updates missing translations and fixes mistranslations
Laravel-Lang/lang pull request #1864
Opened 2021-09-26 13:22 UTC by ordago

2021-09-27 13:28 UTC, caouecs requested changes

2021-09-27 13:28 UTC, caouecs commented on locales/ca/ca.json
> +    "Thanks,": "Gràcies",
Gràcies,

2021-09-27 14:01 UTC, ordago commented on locales/ca/ca.json
> +    "Thanks,": "Gràcies",
Done 👍

2021-09-28 21:49 UTC, merged

2021-09-28 21:49 UTC, caouecs commented
Gràcies