[de] Update Exclusion list
Laravel-Lang/lang pull request #1866
Opened 2021-09-27 13:47 UTC by sotten

add `minute` and `name` to Exclusion list avoid missing translation in `validation-attributes.php`.

2021-09-27 13:58 UTC, andrey-helldar commented
@caouecs, wait, don't take PR. I need to check.

@sotten, the exception file should contain the keys, but if I specify `name` or `attributes.name`, the `php app/excludes.php` script removes those values.

I will fix it shortly.

2021-09-27 15:56 UTC, andrey-helldar requested changes
@caouecs, PR https://github.com/Laravel-Lang/lang/pull/1867 for fix comparing already pushed.

2021-09-27 15:56 UTC, andrey-helldar commented on excludes/de.php
> +    'minute',
Replace with `Minute` (value)

2021-09-27 15:56 UTC, andrey-helldar commented on excludes/de.php
> +    'name',
Remove this line (`Name` already defined).

2021-09-28 07:13 UTC, andrey-helldar approved these changes

2021-09-28 08:35 UTC, andrey-helldar commented
@caouecs, it's ok.

2021-09-28 21:50 UTC, merged

2021-09-28 21:50 UTC, caouecs commented
Danke