Update Fa translation
Laravel-Lang/lang pull request #1900
Opened 2021-11-02 15:20 UTC by amirmojiry

2021-11-02 21:25 UTC, caouecs requested changes

2021-11-02 21:25 UTC, caouecs commented on locales/fa/fa.json
> +    "Press \/ to search": "برای جستجو \/ را بزنید",
\\/

2021-11-02 21:28 UTC, caouecs commented
Hello @amirmojiry,
I have two proposes for fa.json ( see #1891 ), and I don't know how to choose.

Can you review the other PR and check with yours ?

2021-11-03 14:09 UTC, amirmojiry commented
Hi @caouecs,
I've checked the other PR, and I think it's more comprehensive. So, it's better to close my PR and continue with the #(1891).

2021-11-03 17:00 UTC, closed without merging