Missing translation to fr
Laravel-Lang/lang pull request #1972
Opened 2022-01-21 12:58 UTC by Gallyan

2022-01-21 13:00 UTC, andrey-helldar approved these changes

2022-01-21 13:09 UTC, andrey-helldar approved these changes

2022-01-21 13:33 UTC, caouecs commented on locales/fr/fr.json
> +    "If you did not receive the email": "Si vous n'avez pas reçu cet email",
email => e-mail

pour la cohérence

2022-01-21 13:34 UTC, caouecs requested changes

2022-01-21 13:34 UTC, caouecs commented on locales/fr/fr.json
> +    "If you did not receive the email": "Si vous n'avez pas reçu cet email",
email => e-mail

pour la cohérence

2022-01-21 14:15 UTC, Gallyan commented on locales/fr/fr.json
> +    "If you did not receive the email": "Si vous n'avez pas reçu cet email",
C'est corrigé

2022-01-21 18:49 UTC, andrey-helldar approved these changes

2022-01-21 21:36 UTC, andrey-helldar commented
Oh, sorry, I was restoring the branch name and forgot to move the PR before this. I'll fix it now.

2022-01-22 11:20 UTC, WhereIsLucas approved these changes

2022-01-24 15:40 UTC, merged

2022-01-24 15:40 UTC, andrey-helldar commented
Merci