Updating translation keys for Brazilian Portuguese
Laravel-Lang/lang pull request #2000
Opened 2022-01-24 18:26 UTC by EuCarlos

2022-01-24 19:29 UTC, andrey-helldar requested changes

2022-01-24 19:29 UTC, andrey-helldar commented on locales/pt_BR/pt_BR.json
> +    "Have a coupon code?": "Tem um código de cupom?Have a coupon code?",
```suggestion
    "Have a coupon code?": "Tem um código de cupom?",
```

2022-01-24 20:51 UTC, andrey-helldar approved these changes

2022-01-24 20:51 UTC, andrey-helldar commented
Thank you

2022-01-24 20:51 UTC, merged

2022-01-25 11:37 UTC, EuCarlos commented
You're welcome, I'll contribute more.