[vi] translation
Laravel-Lang/lang pull request #2003
Opened 2022-01-25 14:40 UTC by ntvan711

2022-01-25 14:48 UTC, andrey-helldar requested changes

2022-01-25 14:48 UTC, andrey-helldar commented on locales/vi/vi.json
> +    "click here to request another": "Click vào đây để tạo yêu cầu khác",
Is it correct that in your version the sentence starts with a capital letter?

2022-01-25 14:48 UTC, andrey-helldar commented on locales/vi/vi.json
> +    "If you did not receive the email": "Nếu bạn không nhận được email.",
```suggestion
    "If you did not receive the email": "Nếu bạn không nhận được email",
```

The full stop at the end of the sentence is redundant.

2022-01-25 15:14 UTC, andrey-helldar requested changes

2022-01-25 15:14 UTC, andrey-helldar commented on locales/vi/validation-inline.php
> +    'declined'             => 'Giá trị này phải bị từ chối..',
```suggestion
    'declined'             => 'Giá trị này phải bị từ chối.',
```
Extra full stop at the end of a sentence.

2022-01-25 15:14 UTC, andrey-helldar commented on locales/vi/validation-inline.php
> +    'mac_address'          => 'Giá trị phải là địa chỉ MAC hợp lệ',
Missing full stop at the end of a sentence.

2022-01-26 02:34 UTC, dinhquochan commented on locales/vi/vi.json
> +    "click here to request another": "click vào đây để tạo yêu cầu khác",
Yes @andrey-helldar, Its mean "Nhấn"/ "Bấm" but "Click" is common.

2022-01-26 02:37 UTC, dinhquochan requested changes

2022-01-26 02:37 UTC, dinhquochan commented on locales/vi/vi.json
> +    "E-Mail Address": "Địa chỉ Emails",
It's should be "Email" and upcasse "C" letter.

2022-01-26 02:37 UTC, dinhquochan commented on locales/vi/vi.json
> +    "Verify Your Email Address": "Xác minh địa chỉ email của bạn",
Upcase all first letters.

2022-01-26 03:49 UTC, dinhquochan approved these changes
Nice, Thanks @ntvan711

2022-01-26 07:55 UTC, andrey-helldar commented
Obrigado

2022-01-26 07:55 UTC, merged