[ru] fix translations
Laravel-Lang/lang pull request #2024
Opened 2022-02-04 16:03 UTC by jdeeline

I have updated the translation and also corrected some errors.

2022-02-04 16:11 UTC, andrey-helldar commented
В формах понятие "поле" итак подразумевает значение поля, зачем изменять? Какие мотивы?

2022-02-04 16:15 UTC, andrey-helldar commented
В формах понятие "поле" итак подразумевает "значение поля", зачем изменять?

Если уж и изменять, то просто убирать слово "поле", оставив ":attribute должен быть...", дабы смысл был как в оригинале - "the email must be..."

2022-02-04 16:42 UTC, jdeeline commented
> В формах понятие "поле" итак подразумевает "значение поля", зачем изменять?
> 
> Если уж и изменять, то просто убирать слово "поле", оставив ":Attribute должен быть...", дабы смысл был как в оригинале - "the email must be..."

Есть поле, а есть значение, которое это поле содержит и которое проверяется валидатором. По аналогии с тегом input и атрибутом value: одно отображается на веб-странице, другое - передаётся на сервер.

Файл validation.php уже содержит аналогичные исправления: https://github.com/Laravel-Lang/lang/blob/master/locales/ru/validation.php#L54

2022-02-04 18:02 UTC, jdeeline commented
> В плане поля и значения поля я не согласен, так как валидатор обрабатывает то, что поле ему передаёт, таким образом, можно сказать что значение поля и есть поле, но с лексической точки зрения, и в ходе проведенного опроса, соглашусь, вариант "значение поля" выглядит интуитивно понятнее большинству.
> 
> В таком случае, не могли бы Вы обновить все ключи перевода?

Правки вносил в тех местах, где это особенно резало глаз. Да и кажется, что не везде такая замена уместна.

Например, в строке "Поле :attribute содержит недействительный URL" оправдано использование слова "поле". Если употребить вместо него словосочетание "Значение поля", на мой взгляд, необходимо изменить и остальную часть строки, например: "Значение поля :attribute не является действительным URL". В противном случае сообщение об ошибке воспринимается так, будто валидатор искал подстроку в строке, а не проверял значение целиком.

В любом случае, просмотрю ещё раз остальные ключи. Возможно, что-то упустил и действительно стоит обновить.

2022-02-04 18:27 UTC, andrey-helldar commented
Использование смешанного стиля ("поле" и "значение поля") также начнёт резать глаза при попадании таких элементов на форму особенно тем, у кого список ошибок валидатора выводятся не под каждым полем, а списком.

Как по мне, то лучше всё привести к одному типу. Вы можете исправить столько значений, на сколько хватит сил, а я могу закончить начатое.

2022-02-04 18:30 UTC, andrey-helldar commented
Использование смешанного стиля ("поле" и "значение поля") также начнёт резать глаза при попадании таких элементов на форму особенно тем, у кого список ошибок валидатора выводятся не под каждым полем, а списком.

Как по мне, то лучше всё привести к одному виду даже если потребуется обновить текст. Проблема в том, что в оригинале описания читаются, а при переводе на другие языки фразы всегда нужно оптимизировать. Вон, с испанском тоже в том году столкнулись с некоторыми моментами, когда в английском, немецком и ещё каких-то языках написано и понимается одно, а в русском да испанском фраза звучит дико, так как смысл напрямую зависел от контекста, которого не было в тех строках. Думали как лучше исправить.

Вы можете исправить столько значений, на сколько хватит сил, а я могу закончить начатое.

2022-02-05 08:49 UTC, jdeeline commented
> Использование смешанного стиля ("поле" и "значение поля") также начнёт резать глаза при попадании таких элементов на форму особенно тем, у кого список ошибок валидатора выводятся не под каждым полем, а списком.
> 
> Как по мне, то лучше всё привести к одному виду даже если потребуется обновить текст. Проблема в том, что в оригинале описания читаются, а при переводе на другие языки фразы всегда нужно оптимизировать. Вон, с испанском тоже в том году столкнулись с некоторыми моментами, когда в английском, немецком и ещё каких-то языках написано и понимается одно, а в русском да испанском фраза звучит дико, так как смысл напрямую зависел от контекста, которого не было в тех строках. Думали как лучше исправить.
> 
> Вы можете исправить столько значений, на сколько хватит сил, а я могу закончить начатое.

Полагаю, смешанного стиля всё же не получится избежать. Для ключей prohibited* и required* выглядит уместным именно слово "поле".

Обновил перевод для ключей, где это, на мой взгляд, было уместно, а также исправил некоторые ошибки.

2022-02-05 10:27 UTC, andrey-helldar commented
Я правильно понимаю, что Вы закончили с переводами? Могу их проверить?

2022-02-05 10:38 UTC, jdeeline commented
> Я правильно понимаю, что Вы закончили с переводами? Могу их проверить?

Да, закончил. Проверьте, пожалуйста.

2022-02-05 10:49 UTC, andrey-helldar requested changes

2022-02-05 10:49 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'current_password'     => 'Некорректный пароль.',
```suggestion
    'current_password'     => 'Значение поля :attribute содержит некорректный пароль.',
```

В данном файле все сообщения об ошибках обязательно должны ссылаться на конкретное поле.

2022-02-05 10:49 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'date_format'          => 'Значение поля :attribute не соответствует формату :format.',
```suggestion
    'date_format'          => 'Значение поля :attribute не соответствует формату даты :format.',
```

2022-02-05 10:49 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
```suggestion
    'file'                 => 'В значении поля :attribute должен быть файл.',
```

2022-02-05 10:49 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'enum'                 => 'Выбранное значение для :attribute ошибочно.',
В случае с применением слова "ошибочно" первая же возникшая мысль - "а в чём, собственно, ошибка?".

В случае с применением слова "некорректно" такой мысли не возникает и текст ошибки воспринимается как данность.

2022-02-05 10:49 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'exists'               => 'Выбранное значение для :attribute ошибочно.',
В случае с применением слова "ошибочно" первая же возникшая мысль - "а в чём, собственно, ошибка?".

В случае с применением слова "некорректно" такой мысли не возникает и текст ошибки воспринимается как данность.

2022-02-05 10:59 UTC, jdeeline commented on locales/ru/validation.php
> +    'current_password'     => 'Некорректный пароль.',
Ориентировался на то, что есть в english, там название атрибута не подставляется: _The password is incorrect._

2022-02-05 11:03 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'current_password'     => 'Некорректный пароль.',
Тейлор много странностей вносит, что ж, оставим.

2022-02-05 11:06 UTC, jdeeline commented on locales/ru/validation.php
> +    'exists'               => 'Выбранное значение для :attribute ошибочно.',
А в случае с in и not_in такой мысли не возникает?
https://github.com/Laravel-Lang/lang/blob/master/locales/ru/validation.php#L64
https://github.com/Laravel-Lang/lang/blob/master/locales/ru/validation.php#L99

2022-02-05 11:18 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'exists'               => 'Выбранное значение для :attribute ошибочно.',
Возникает, но до сегодняшнего дня не обращал внимания. После Вашего PR в моих планах привести в человеческий вид все остальные переводы.

2022-02-05 12:02 UTC, jdeeline commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
Читается как-то... Будто файл должен являться лишь частью значения.

2022-02-05 12:44 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
Как такой вариант: "В поле :attribute должен быть указан файл."?

2022-02-05 13:40 UTC, jdeeline commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
> Да, при переводе есть такие спорные моменты.
> 
> Как на счёт такого варианта: "В поле :attribute должен быть указан файл."?

Вроде бы, хорошо. Если это сообщение выводится на веб-странице, конечно, лучше воспринималось бы слово «выбран», но если учитывать и в контексте ответа API на посланный curl`ом запрос, действительно, уместнее употребить «указан».

Кстати, а что с вариантом «Значением поля :attribute должен быть файл» было не так?

2022-02-05 14:11 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
Есть небольшое ощущение что файл должен быть именно в значении... То есть сам файл, а не ссылка на него. При этом, слово "ссылка" в отношение выбора файла лучше не использовать, а то скажут "как сюда урл засунуть")

2022-02-05 14:49 UTC, jdeeline commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
> Есть небольшое ощущение что файл должен быть именно в значении... То есть сам файл, а не ссылка на него. При этом, слово "ссылка" в отношение выбора файла лучше не использовать, а то скажут "как сюда урл засунуть")

Так файл ведь и должен быть именно в значении: успешно загруженным во временную директорию и переданным валидатору в качестве \Illuminate\Http\UploadedFile. Если скормить валидатору вместо объекта UploadedFile строку «это не файл», он как раз и выбросит это сообщение.
Если перевод «Значением поля :attribute должен быть файл» вызывает мысль о ссылке на файл, то и оригинал «The :attribute must be a file» должен вызывать такие же ассоциации (_Значением поля Видео должен быть файл / Видео должно быть файлом_).

2022-02-05 15:12 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
В том и интерес, что если в строке "The :attribute must be a file" использовать название поля, например, "photo", то фраза "The photo must be file" будет звучать как "Фотография должна быть файлом", а не "Значение поля фотография должно быть файлом". Я об этом говорю.

2022-02-05 15:23 UTC, jdeeline commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
Хорошо. Вами предложенный вариант закоммитил.

2022-02-05 18:04 UTC, andrey-helldar commented on locales/ru/validation.php
> +    'file'                 => 'Значением поля :attribute должен быть файл.',
Кстати, если брать отношение только к API, то все эти сообщения также некорректны ибо данные идут не в значении полей, а в ассоциативном массиве, по сути. Таким образом, привязываемся не к полям и значениям, а к ключам массива.

2022-02-05 18:05 UTC, merged

2022-02-05 18:05 UTC, andrey-helldar commented
Спасибо