nl-NL (Dutch) update
Laravel-Lang/lang pull request #2087
Opened 2022-03-25 15:09 UTC by JappaWakka

Tweaked the Dutch localization a bit

2022-03-25 16:40 UTC, andrey-helldar requested changes
Fix line breaks in all files.

The commit does not have to update absolutely all rows.

2022-03-25 16:41 UTC, JappaWakka commented
> Fix line breaks in all files.
> 
> The commit does not have to update absolutely all rows.

what needs to be fixed and how do I change the second part

2022-03-25 17:10 UTC, andrey-helldar commented
@JappaWakka, see a screenshoots:

From me:

![image](https://user-images.githubusercontent.com/10347617/160168633-a2226c37-ca48-4cd7-84f9-70972ceedc98.png)

From you:

![image](https://user-images.githubusercontent.com/10347617/160168680-6a85c296-5644-4910-88b8-85d565ec33a7.png)

2022-03-25 17:19 UTC, andrey-helldar commented
I replaced the commit

2022-03-25 17:20 UTC, andrey-helldar approved these changes

2022-03-25 17:21 UTC, andrey-helldar approved these changes

2022-03-25 17:21 UTC, andrey-helldar commented on locales/nl/auth.php
> +];
```suggestion
];

```

2022-03-25 17:21 UTC, andrey-helldar commented on locales/nl/passwords.php
> +];
```suggestion
];

```

2022-03-25 17:21 UTC, andrey-helldar commented on locales/nl/validation.php
> +];
```suggestion
];

```

2022-03-25 20:24 UTC, andrey-helldar approved these changes

2022-03-28 22:49 UTC, andrey-helldar commented
@WhereIsLucas, can you check this PR?

2022-03-29 05:33 UTC, WhereIsLucas approved these changes

2022-03-29 07:27 UTC, merged

2022-03-29 07:27 UTC, andrey-helldar commented
Dankjewel