fix(fr): missing translations
Laravel-Lang/lang pull request #2135
Opened 2022-04-14 09:12 UTC by NicoBernardet

Ajout des traductions manquantes

2022-04-14 09:36 UTC, andrey-helldar requested changes

2022-04-14 09:36 UTC, andrey-helldar commented on locales/fr/fr.json
> +    "E-Mail Address": "Adresse e-mail ",
Unnecessary space at the end of the line.

2022-04-14 09:44 UTC, caouecs requested changes

2022-04-14 09:44 UTC, caouecs commented on locales/fr/fr.json
> +    "Are you sure you want to stop impersonating?": "Êtes-vous sûr de vouloir arrêter d'utiliser un autre compte ?",
sûr(e) : pour garder l'homogénéité

2022-04-14 09:44 UTC, caouecs commented on locales/fr/fr.json
> +    "The resource was attached!": "La resource a été jointe",
La donnée ? Vu qu'ailleurs on utilise donnée au lieu de resource

2022-04-17 09:19 UTC, andrey-helldar requested changes

2022-04-17 09:19 UTC, andrey-helldar commented on locales/fr/fr.json
> +    "There are no new notifications.": "Il n'y a pas de nouvelles notifications",
```suggestion
    "There are no new notifications.": "Il n'y a pas de nouvelles notifications.",
```

2022-04-17 09:20 UTC, andrey-helldar approved these changes

2022-04-18 07:30 UTC, merged

2022-04-18 07:30 UTC, caouecs commented
Merci