zh-cn new translations
Laravel-Lang/lang pull request #2179
Opened 2022-05-14 06:32 UTC by BuleWhale

update and edit translations

2022-05-14 09:41 UTC, overtrue requested changes

2022-05-14 09:41 UTC, overtrue commented on locales/zh_CN/validation-inline.php
> +            'rule-name' => '自定义信息',
这个不用翻译的

2022-05-14 09:41 UTC, overtrue commented on locales/zh_CN/validation.php
> +            'rule-name' => '自定义信息',
同理不用翻译

2022-05-14 09:41 UTC, overtrue commented on locales/zh_CN/zh_CN.json
> +    "Having second thoughts about cancelling your subscription? You can instantly reactive your subscription at any time until the end of your current billing cycle. After your current billing cycle
其实这里是表达犹豫不决打算取消订阅

2022-05-14 09:57 UTC, BuleWhale commented
原来如此，感谢指导。

2022-05-14 10:01 UTC, BuleWhale commented
个人提一个小建议，在需要翻译的地方后面加 `TO DO`

2022-05-14 10:18 UTC, overtrue commented
> 个人提一个小建议，在需要翻译的地方后面加 `//TO DO`

会自动生成一个待更新页面的

2022-05-14 12:33 UTC, overtrue approved these changes

2022-05-15 01:26 UTC, merged

2022-05-15 01:26 UTC, andrey-helldar commented
谢谢