Update ro.json
Laravel-Lang/lang pull request #2197
Opened 2022-05-28 19:40 UTC by Van4kk

- grammar corrections
- translation corrections
- added "Meeting" because it was translated wrong to "Reunion"

2022-05-28 20:27 UTC, Van4kk commented
whats wrong ?

2022-05-28 21:09 UTC, andrey-helldar requested changes

2022-05-28 21:09 UTC, andrey-helldar commented on locales/ro/ro.json
> +    "Meeting": "Întalnire",
No need to add your own words. This package does an automatic comparison of all keys.

If you need to create your own set of translations, you can use the [`template`](https://github.com/Laravel-Lang/translations-template).

2022-05-28 21:09 UTC, andrey-helldar commented on locales/ro/ro.json
> -    "Micronesia, Federated States of": "Micronesia, Federated States of",
You have deleted the key. So you don't have to do it.

`Micronesia, Federated States Of` !== `Micronesia, Federated States of`

2022-05-28 21:34 UTC, Van4kk commented
aaah my bad then

2022-05-28 21:41 UTC, Van4kk commented
all good now ?

2022-05-29 09:03 UTC, andrey-helldar approved these changes

2022-05-29 09:03 UTC, andrey-helldar commented on locales/ro/ro.json
> +    "Micronesia, Federated States of": "Micronezia",
```suggestion
    "Micronesia, Federated States of": "Statele Federate ale Microneziei",
```

2022-05-29 09:04 UTC, merged

2022-05-29 09:05 UTC, andrey-helldar commented
Mulțumim