[hi] Update hindi
Laravel-Lang/lang pull request #2297
Opened 2022-08-07 13:00 UTC by nishadil

[hi] Update hindi

2022-08-07 18:45 UTC, andrey-helldar requested changes
Is it true that some sentences have a space before the `|` and some do not?

For example:

```
"accepted_if": ":Attribute को ज़रूर स्वीकार किया जाना चाहिए जब :other :value हो ।",
"mac_address": "इस फ़ील्ड में एक मान्य MAC address होना चाहिए।"
```

2022-08-07 18:45 UTC, andrey-helldar commented on locales/hi/php-inline.json
> +    "accepted_if": ":Attribute को ज़रूर स्वीकार किया जाना चाहिए जब :other :value हो ।",
In the inline translation file, you do not need to access the attribute.

For example:

> Main: The :attribute must be accepted when :other is :value.
> Inline: This field must be accepted when :other is :value.

2022-08-07 18:45 UTC, andrey-helldar commented on locales/hi/php-inline.json
> +    "declined_if": ":Attribute को ज़रूर अस्वीकार किया जाना चाहिए जब :other :value हो ।",
In the inline translation file, you do not need to access the attribute.

For example:

> Main: The :attribute must be declined when :other is :value.
> Inline: This field must be declined when :other is :value.

2022-08-07 18:46 UTC, andrey-helldar commented
If you want to add new changes to a PR, you don't need to close the old one and create a new one PR. It is enough to create a commit and execute the `git push` command. All new changes will go into the previously created PR, provided the changes are made to the same branch.

2022-08-08 14:53 UTC, nishadil commented
> Is it true that some sentences have a space before the `|` and some do not?
> 
> For example:
> 
> ```
> "accepted_if": ":Attribute को ज़रूर स्वीकार किया जाना चाहिए जब :other :value हो ।",
> "mac_address": "इस फ़ील्ड में एक मान्य MAC address होना चाहिए।"
> ```

Actually, in Hindi language symbol `।` used in two places and meaning of it depends on where we used it. like "होना", "बड़ा" etc ends with similar symbol while these are complete words, so at the end of sentences we mostly use some space between last word and sentences closer `।` to avoid creating any reading illusion.

2022-08-08 15:51 UTC, merged