Update json.json
Laravel-Lang/lang pull request #2311
Opened 2022-08-10 06:03 UTC by AzadGh95

change فایل to مورد
it's more correct

2022-08-10 09:31 UTC, andrey-helldar approved these changes
It's ok for me

2022-08-11 06:32 UTC, ariaieboy commented
> It's ok for me

line 59 must be reverted but other changes are good.

2022-08-11 08:07 UTC, andrey-helldar requested changes

2022-08-11 08:07 UTC, andrey-helldar commented on locales/fa/json.json
> +    "Are you sure you want to delete this file?": "آیا از حذف این مورد مطمئن هستید؟",
```suggestion
    "Are you sure you want to delete this file?": "آیا از حذف این فایل مطمئن هستید؟",
```

2022-08-11 08:08 UTC, andrey-helldar approved these changes
ممنون

2022-08-11 08:08 UTC, merged