[vi]: Translation update
Laravel-Lang/lang pull request #2332
Opened 2022-08-21 17:25 UTC by ntvan711

2022-08-21 17:41 UTC, andrey-helldar requested changes

2022-08-21 17:41 UTC, andrey-helldar commented on locales/vi/json.json
> +    "The provided two factor recovery code was invalid.": "Mã xác minh hai yếu tố đã cung cấp không hợp lệ",
```suggestion
    "The provided two factor recovery code was invalid.": "Mã xác minh hai yếu tố đã cung cấp không hợp lệ.",
```

2022-08-22 01:09 UTC, dinhquochan approved these changes
Cảm ơn bạn.

2022-08-22 08:55 UTC, andrey-helldar approved these changes
Cảm ơn

2022-08-22 08:55 UTC, merged