Key translations for ro/json-inline.json
Laravel-Lang/lang pull request #2333
Opened 2022-08-21 18:37 UTC by Van4kk

2022-08-21 19:40 UTC, andrey-helldar requested changes

2022-08-21 19:40 UTC, andrey-helldar commented on locales/ro/json-inline.json
> +    "The given :attribute has appeared in a data leak. Please choose a different :attribute.": "Acest câmp dat a apărut într-o scurgere de date. Vă rugăm să alegeți un alt câmp"
```suggestion
    "The given :attribute has appeared in a data leak. Please choose a different :attribute.": "Acest câmp dat a apărut într-o scurgere de date. Vă rugăm să alegeți un alt câmp."
```

2022-08-21 21:57 UTC, andrey-helldar approved these changes
Mulțumim

2022-08-21 21:57 UTC, merged

2022-08-22 10:08 UTC, Van4kk commented
Cu placere !