Update json.json
Laravel-Lang/lang pull request #2398
Opened 2022-09-21 12:24 UTC by alirezavaker

Complete the translation process

2022-09-21 12:40 UTC, andrey-helldar requested changes

2022-09-21 12:40 UTC, andrey-helldar commented on locales/fa/json.json
> +  the team?": "آیا مطمئن هستید که می‌خواهید این شخص را از تیم حذف کنید؟",
Incorrect json

2022-09-21 16:43 UTC, ariaieboy requested changes

2022-09-21 16:43 UTC, ariaieboy commented on locales/fa/json.json
> +    "Logs": "تاریخچه ها",
کلمه Log به عنوان تاریخچه خیلی معنا نداره و معمولا تاریخچه هم ترجمه نمیشه به نظر من بهتر هست برای Log بجای ترجمه از کلمه `لاگ` استفاده کنید.

2022-10-08 14:49 UTC, andrey-helldar commented
@alirezavaker, can you fix this PR?

2022-10-08 22:05 UTC, ariaieboy commented
> @alirezavaker, can you fix this PR?

if you give me access i can push the fixs

2022-10-17 20:41 UTC, andrey-helldar commented
@alirezavaker, ping

2022-10-18 07:49 UTC, andrey-helldar commented
Fixed in https://github.com/Laravel-Lang/lang/pull/2420

2022-10-18 07:49 UTC, closed without merging