[bn] Translation update
Laravel-Lang/lang pull request #2407
Opened 2022-09-30 12:49 UTC by arman-arif

2022-09-30 13:58 UTC, andrey-helldar requested changes

2022-09-30 13:58 UTC, andrey-helldar commented on locales/bn/php-inline.json
> +    "required_if_accepted": "এই ক্ষেত্রটি প্রয়োজন হয় যখন :other গৃহীত হয়",
```suggestion
    "required_if_accepted": "এই ক্ষেত্রটি প্রয়োজন হয় যখন :other গৃহীত হয়.",
```

2022-09-30 13:58 UTC, andrey-helldar commented on locales/bn/php.json
> +    "required_if_accepted": ":attribute ক্ষেত্রটি প্রয়োজন হয় যখন :other গৃহীত হয়",
```suggestion
    "required_if_accepted": ":attribute ক্ষেত্রটি প্রয়োজন হয় যখন :other গৃহীত হয়.",
```

2022-09-30 14:00 UTC, andrey-helldar requested changes
In some places sentences end with a full stop (`.`), and in others with a slash (`|`).

Which option is correct?

2022-09-30 14:00 UTC, andrey-helldar commented on locales/bn/php-inline.json
>      "required_array_keys": "এই ক্ষেত্রটিতে অবশ্যই :values এর জন্য এন্ট্রি থাকতে হবে",
```suggestion
    "required_array_keys": "এই ক্ষেত্রটিতে অবশ্যই :values এর জন্য এন্ট্রি থাকতে হবে.",
```

2022-09-30 14:00 UTC, andrey-helldar commented on locales/bn/php.json
>      "required_array_keys": ":Attribute ফিল্ডে অবশ্যই :values এর জন্য এন্ট্রি থাকতে হবে",
```suggestion
    "required_array_keys": ":Attribute ফিল্ডে অবশ্যই :values এর জন্য এন্ট্রি থাকতে হবে.",
```

2022-10-01 07:17 UTC, arman-arif commented on locales/bn/php-inline.json
>      "required_array_keys": "এই ক্ষেত্রটিতে অবশ্যই :values এর জন্য এন্ট্রি থাকতে হবে",
In bengali (.) = (।)

2022-10-01 07:20 UTC, arman-arif commented
In Bengali  (`.`) = (`।`)

I will change all `.` and push a commit. Please wait until that.

2022-10-01 08:14 UTC, arman-arif commented
Made some correction and all (`.`) at the end of sentences are now changed to (`। `)

2022-10-01 11:06 UTC, andrey-helldar commented
@arman-arif, understood, thanks 🤝

2022-10-01 11:06 UTC, andrey-helldar approved these changes
তোমাকে ধন্যবাদ

2022-10-01 11:06 UTC, merged

2022-10-01 12:51 UTC, arman-arif commented
> তোমাকে ধন্যবাদ

স্বাগতম