[fr] Add missing translations and small corrections in FR json.json
Laravel-Lang/lang pull request #2432
Opened 2022-10-20 15:31 UTC by cbouvat

2022-10-20 16:20 UTC, cbouvat commented
@andrey-helldar sorry for the name of the pull request, I followed the doc 😥

2022-10-20 16:21 UTC, andrey-helldar commented
@cbouvat, no problem 🤝

2022-10-20 17:17 UTC, caouecs requested changes

2022-10-20 17:17 UTC, caouecs commented on locales/fr/json.json
> +    "Drop file or click to choose": "Déposez le fichier ou cliquez pour choisir",
Déposez ou Déposer ?

2022-10-20 17:17 UTC, caouecs commented on locales/fr/json.json
> +    "Unknown": "Inconnue",
Inconnu(e)

2022-10-20 17:25 UTC, WhereIsLucas requested changes
Je pense que les verbes doivent être à l'infinitif

2022-10-20 18:16 UTC, cbouvat commented on locales/fr/json.json
> +    "Drop file or click to choose": "Déposez le fichier ou cliquez pour choisir",
Je suis d’accord avec « déposer »

2022-10-20 18:18 UTC, cbouvat commented
Je vais relire les traductions et je vais les passer à l’infinitif

2022-10-21 09:48 UTC, cbouvat commented
J'ai fait plusieurs modifications après relecture des traductions
- Les majuscules
- "Subcription" en "abonnement", ce n'était pas cohérent dans l'ensemble du fichier
- Des passages à l'infinitif

J'ai fait aussi une autre pull-request ici : https://github.com/Laravel-Lang/attributes/pull/54

2022-10-21 12:16 UTC, merged

2022-10-21 12:16 UTC, caouecs commented
C'est bon pour moi, merci

2022-10-21 12:33 UTC, WhereIsLucas commented
Bon pour moi aussi