[hr]: Added missing translations
Laravel-Lang/lang pull request #2465
Opened 2022-11-13 23:36 UTC by jure-knezovic

- Added missing translations
- Improved few of the machine translated translations

Hi there, I am starting a project which will be completely in croatian, so I will try to fix grammar & provide regular PRs in all of the other machine translated stuff.

2022-11-14 12:58 UTC, andrey-helldar requested changes

2022-11-14 12:58 UTC, andrey-helldar commented on locales/hr/json-inline.json
> +    "The :attribute must be a valid role.": ":attribute mora biti valjana uloga.",
Inline translations must not refer to the attribute name.

Default translation:
> "The :attribute must be a valid role.": "The :attribute field must be a valid role.",

Inline translation:
> "The :attribute must be a valid role.": "This field must be a valid role.",


https://laravel-lang.com/contributing.html#how-can-i-add-a-language-in-this-project

2022-11-14 12:58 UTC, andrey-helldar commented on locales/hr/json.json
> +    ":days day trial": "probno razdoblje od :days dana",
A sentence must begin with a capital letter, unless the grammar rules of your language suggest otherwise.

2022-11-14 12:58 UTC, andrey-helldar commented on locales/hr/json.json
> +    "Email Address": "e-mail adresa",
```suggestion
    "Email Address": "E-mail adresa",
```

2022-11-14 12:58 UTC, andrey-helldar commented on locales/hr/php-inline.json
> +    "between.array": "mora sadržavati :min - :max stavki.",
A sentence must begin with a capital letter, unless the grammar rules of your language suggest otherwise.

2022-11-14 20:40 UTC, andrey-helldar commented on locales/hr/php-inline.json
> +    "uuid": "Ovo polje mora sadržavati valjani UUID.",
```suggestion
    "uuid": "Ovo polje mora sadržavati valjani UUID."
```

2022-11-14 20:42 UTC, andrey-helldar approved these changes
Hvala

2022-11-14 20:42 UTC, merged

2022-11-14 20:48 UTC, jure-knezovic commented
yep

2022-11-15 07:38 UTC, andrey-helldar commented
Do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

2022-11-16 14:31 UTC, jure-knezovic commented
Sure, i can do it for croatian, serbian(latin), serbian(montenegro) and bosnian.

2022-11-16 14:51 UTC, andrey-helldar commented
It would be cool. @caouecs, can you add @jure-knezovic to the our team?

2022-11-28 14:48 UTC, andrey-helldar commented
@caouecs, ping

2022-11-28 16:57 UTC, caouecs commented
done

sorry for the lag