[vi]: update translations
Laravel-Lang/lang pull request #2501
Opened 2022-11-28 15:03 UTC by datlechin

2022-12-01 03:26 UTC, dinhquochan requested changes

2022-12-01 03:26 UTC, dinhquochan commented on locales/vi/json.json
> +    "Drop files or click to choose": "Kéo thả hoặc nhấp để chọn tệp tin",
Use `click`, this word could not be translated.

2022-12-01 03:26 UTC, dinhquochan commented on locales/vi/json.json
> +    "Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.": "Khi tài khoản
```suggestion
    "Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.": "Khi tài khoản của bạn bị xoá, tất cả tài nguyên và dữ liệu của tài khoản đó sẽ bị xoá vĩnh viễn. Vui lòng nhập mật khẩu của bạn đã xác nhận nếu bạn muốn xoá vĩnh viễn tài khoản của bạn.",
```

2022-12-01 03:26 UTC, dinhquochan commented on locales/vi/json.json
> +    "Soft Deleted": "Xoá tạm thời",
```suggestion
    "Soft Deleted": "Xoá Tạm Thời",
```

2022-12-01 03:26 UTC, dinhquochan commented on locales/vi/json.json
> +    "Unknown": "Không xác định",
```suggestion
    "Unknown": "Không Xác Định",
```

2022-12-05 04:40 UTC, dinhquochan approved these changes
LGTM.

2022-12-05 07:45 UTC, andrey-helldar approved these changes
Cảm ơn

2022-12-05 07:46 UTC, merged