[fr]: Updated translations
Laravel-Lang/lang pull request #2591
Opened 2023-01-13 11:26 UTC by wblondel

Updated as many translations as I can. It's a bit difficult to get the context without access to the paid plugins.

2023-01-13 13:05 UTC, caouecs requested changes
Merci

2023-01-13 13:05 UTC, caouecs commented on locales/fr/php.json
> +    "team_name_was_updated": " Le nom de votre équipe a été modifié!",
a space between "modifié" and "!"

2023-01-13 13:05 UTC, caouecs commented on locales/fr/php.json
> +    "user_invited_to_join_team": ":UserName vous a invité à joindre son équipe!",
a space between "équipe" and "!"

2023-01-13 13:11 UTC, wblondel commented on locales/fr/php.json
> +    "user_invited_to_join_team": ":UserName vous a invité à joindre son équipe!",
Fixed, thanks!

2023-01-13 13:11 UTC, wblondel commented on locales/fr/php.json
> +    "team_name_was_updated": " Le nom de votre équipe a été modifié!",
Fixed, thanks!

2023-01-14 13:29 UTC, wblondel commented
Hi, sorry I didn't mean to remove request for @WhereIsLucas , I don't know how that happened. I pushed the requested changes.

2023-01-14 14:01 UTC, andrey-helldar commented
@wblondel, don't worry, I fixed it 🤝

2023-01-21 10:53 UTC, andrey-helldar commented
@caouecs, @WhereIsLucas, ping

2023-02-01 07:50 UTC, andrey-helldar commented
@caouecs, @WhereIsLucas, hi! Can you check this PR?

2023-02-01 08:13 UTC, caouecs requested changes
Juste une modification pour inclure tout le monde et ça ira pour moi

2023-02-01 08:13 UTC, caouecs commented on locales/fr/php.json
> +    "you_have_been_invited_to_join_team": "Vous avez été invité à rejoindre l'équipe :teamName !",
Ouf j'ai trouvé un truc à dire ;)

Vous avez été invité(e) à rejoindre l'équipe :teamName !

2023-02-06 14:14 UTC, wblondel commented on locales/fr/php.json
> +    "you_have_been_invited_to_join_team": "Vous avez été invité à rejoindre l'équipe :teamName !",
C'est fait, j'ai corrigé. Egalement dans le fichier json.json

2023-02-06 14:16 UTC, wblondel commented
I applied the requested change, and I also translated additional strings

2023-02-08 19:55 UTC, merged

2023-02-08 19:55 UTC, caouecs commented
merci