Made a bunch of fixes to da locale
Laravel-Lang/lang pull request #3066
Opened 2023-03-31 16:23 UTC by jezzdk

I didn't go through all of them to be honest, just the ones I've come across and some I noticed while I was editing the file.

2023-04-08 13:49 UTC, andrey-helldar commented
@jensstigaard, can you check this PR?

2023-04-11 10:47 UTC, jensstigaard requested changes
I have made a review of the changes with comments for suggested adjustments to the danish translations. Overall the changes looks ok. The adjustments suggest are minor.

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Copy To Clipboard": "Kopier til Udklipsholder",
"udklipsholder" should remain lower case.

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Detach Resource": "Frigør Ressource",
"Ressource" should be lower cased

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Detach Selected": "Frigør Valgte",
"Valgte" should be lower cased

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Disable": "Deaktiver",
Should be "Deaktivér" (with accent over e)

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Edit": "Rediger",
Should be "Redigér" (with accent over e)

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Email Address": "Email adresse",
Should be one of either "E-mailadresse", "Email-adresse" or "Mail-adresse"

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Enable": "Aktiver",
Should be "Aktivér" (with accent over e)

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Log In": "Log Ind",
Should be "Log ind" (lowercased i)

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Login": "Logind",
Should be "Log ind"

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Logout": "Logud",
Should be "Log ud"

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Logout Other Browser Sessions": "Logud af andre browsersessioner",
Should be "Log ud af[...]"

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "No :resource matched the given criteria.": "Inger :resource matchede de givne kriterier.",
Should be "Ingen [...]"

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Restore Selected": "Gendan Valgte",
"Valgte" should be lowercased

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "Run Action": "Kør Handling",
Should be "Udfør handling"

2023-04-11 10:47 UTC, jensstigaard commented on locales/da/json.json
> +    "VAT ID": "Moms ID",
Should be "Momsnummer"

2023-04-16 01:39 UTC, andrey-helldar commented
@jensstigaard, can you check this PR again?

2023-04-18 06:54 UTC, jensstigaard commented
> @jensstigaard, can you check this PR again?

Yep!

I amde the decision to make a complete review of the danish translations. I have neglected this for a while. This turned out that a lot of the translations could be improved.
I forked the work of @jezzdk and corrected the reviewed translations, and pushed the corrected translations to my own fork, which now contains more correct translations for danish.
My fork can be found at:
https://github.com/jensstigaard/Laravel-lang/tree/jezzdk/main

I am not aware whats the easiest way to pull this into the main repo. My initial thought are:
 - Approve + accept this pull request
 - Open another pull request based on my fork
 - Approve this pull request

I hope it makes sense.
@andrey-helldar If you agree to this, I will open a pull request for my fork

2023-04-18 07:06 UTC, andrey-helldar commented
@jensstigaard, yes, you can accept this PR and you can create a new one.

@jensstigaard, @jezzdk, Tak!

2023-04-18 07:07 UTC, merged