add translation of pending terms into Spanish
Laravel-Lang/lang pull request #3085
Opened 2023-04-07 00:26 UTC by andresayac

add translation of pending terms into Spanish

2023-04-07 08:39 UTC, andrey-helldar requested changes

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Additional billing information updated successfully.": "La información adicional de facturación se actualizó correctamente",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Payment information updated successfully.": "Información de pago actualizada correctamente",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Please set a default payment method before swapping plans.": "Por favor establece un método de pago predeterminado antes de cambiar de plan",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "The default payment method cannot be removed.": "El método de pago predeterminado no puede ser eliminado",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "You have some unpaid invoices. After updating your default payment method, you may retry the payments via the invoice list below.": "Tienes algunas facturas impagas. Después de actualizar tu mét
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "You will receive an invoice and payment link via email for each billing period.": "Recibirás una factura y un enlace de pago por correo electrónico para cada período de facturación",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Your payment method has been added successfully.": "Tu método de pago ha sido agregado con éxito",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Your payment method will be charged automatically for each billing period.": "Su método de pago será cargado automáticamente para cada período de facturación",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Your subscription has been started successfully.": "Tu suscripción ha sido iniciada con éxito",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Your subscription was successfully updated.": "Tu suscripción se actualizó correctamente",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Your subscription was successfully resumed.": "Tu suscripción se reanudó correctamente",
A full stop is missing at the end of the sentence.

2023-04-07 08:39 UTC, andrey-helldar commented on locales/es/json.json
> +    "Your subscription has been successfully cancelled.": "Tu suscripción ha sido cancelada exitosamente",
A full stop is missing at the end of the sentence.

2023-04-07 15:33 UTC, luisprmat requested changes

2023-04-07 18:04 UTC, merged

2023-04-07 18:05 UTC, andrey-helldar commented
Gracias

2023-04-07 22:33 UTC, andresayac commented
I was reviewing your comments, I appreciate your feedback. I have seen the translation in another pull. I imagine that they use a bot with AI to carry them out, in case I will be attentive to anything that I can contribute

2023-04-08 00:11 UTC, andrey-helldar commented
@andresayac, just Google Translate. No AI.

2023-04-08 00:49 UTC, luisprmat commented
@andresayac, welcome to contribute, although we use Google to translate automatically, we know that Google translations are not perfect and sometimes require some adjustment to make sense in context.

2023-04-08 02:23 UTC, andresayac commented
I'm thinking of generating a project where a JSON file or similar is added to establish some parameters for performing automatic translation using OpenAI. I have been testing it as a native speaker in Spanish and it works very well.

2023-04-08 11:53 UTC, andrey-helldar commented
In our case, the transfer is carried out in the following way:

1. New keys for translation are added;
2. At 01:27 AM, a task is launched that looks for untranslated keys and sends them to Google Translate.
3. The answer from Google writes to a file and creates a PR.
4. We accept it and subsequently correct the translation in accordance with the grammar and punctuation rules of the language. At the same time, we understand that Google Translate in most cases produces a result that is incorrect in terms of grammar. But we also understand that he does an excellent job of conveying meaning. And this is clearly better than showing, for example, the text in English for the Spanish language.

The script does not touch already translated strings.

Your OpenAI connection idea is good, but you may also run into a problem.

For example, I took an [example](https://platform.openai.com/examples/default-translate) text from the official documentation and sent it to the chat. As a result, instead of translating into Spanish and Japanese, he issued the text in Russian. In addition, when trying to translate into Spanish, he indicated a completely different question.

I want to say that with him, too, there may be problems.

Request:
```
Translate this into 1. French, 2. Spanish and 3. Japanese:

What rooms do you have available?

1.
```

Response:
```
Quelles chambres avez-vous de disponibles?
2.¿ Что можно приобрести?
3. Какие комнаты доступны?
```

The second point contains an incorrect translation. This translates as "What can be purchased?"