[uk]: Updated translation into Ukrainian
Laravel-Lang/lang pull request #3609
Opened 2023-10-25 18:10 UTC by ivanBell199

2023-10-25 20:19 UTC, andrey-helldar requested changes

2023-10-25 20:19 UTC, andrey-helldar commented on locales/uk/json.json
>      "Log out": "Вийти",
```suggestion
    "Log out": "Вийти з системи",
```
Як Ви думаєте, може, тут теж перейменувати ключ, щоб відповідати перекладу інших?

2023-10-25 20:59 UTC, ivanBell199 commented on locales/uk/json.json
>      "Log out": "Вийти",
Мені просто не давала спокою маленька літера в цій фразі 😅 Вона використовується в меню і відразу помітна. Але пізніше я планую переглянути всі переклади і запропонувати більше змін

2023-10-25 22:35 UTC, andrey-helldar commented on locales/uk/json.json
>      "Log out": "Вийти",
Розумію) Це був один із доданих ключів і на ньому спрацював автоперекладач.

2023-10-26 16:35 UTC, andrey-helldar approved these changes
Дякую!

2023-10-26 16:35 UTC, merged