[el]: Updated: Greek json translations
Laravel-Lang/lang pull request #4705
Opened 2024-04-01 12:38 UTC by michaelkonstantinou

Hi

I noticed that some of the translations I used did not make much sense so I changed them. In the meantime I changed some other lines I found that did not make sense but were important (e.g. administrator users was translated to "the users belonging to the administrator")

2024-04-01 13:48 UTC, andrey-helldar requested changes

2024-04-01 13:48 UTC, andrey-helldar commented on locales/el/json.json
> +    "API Token": "API Token",
Add this value to the "_excludes.json" file, otherwise the translation status will show it.

The file is located in the localization folder.

2024-04-01 15:14 UTC, andrey-helldar approved these changes
ευχαριστώ

2024-04-01 15:16 UTC, merged

2024-04-02 12:03 UTC, michaelkonstantinou commented
@andrey-helldar 

If this is not something that I will have to do every day, then I am in!

2024-04-02 14:10 UTC, andrey-helldar commented
@michaelkonstantinou, not every day. Don't worry 🙂

We have an opensource community on a volunteer basis. Each team member decides how much effort to put into the project.

Someone re-reads all translations and corrects them. Someone checks the machine translation. Someone translates new keys before Google Translate gets to them 😂. Someone completes translations (for example, [attributes](https://github.com/Laravel-Lang/attributes) and [actions](https://github.com/Laravel-Lang/actions) projects contain names from real projects, which people decided to share in order not to translate them in final projects).

About initiative, I think it's clear. As for the support of localizations, it happens as follows: as soon as new translation keys are added, whether manually or automatically (the [Lang](https://github.com/Laravel-Lang/lang) project has an automatic download of all Laravel projects that have localizations), I put a command trigger on PR and everyone who wants to update.

Taylor usually posts releases on Tuesdays, and translations are added even less frequently.

How's that? Does that work for you?

2024-04-02 15:42 UTC, michaelkonstantinou commented
Sounds good, yes! 

Now that you mention the two more repositories, it seems that there are a couple more pull-requests that I need to open to fix the machine translations 😆 

Alright, if there are any further details that I need to be aware of, please do inform me, maybe on a personal message since this is a PR. Other than that I would be happy to help. For now, I spotted more translations that need fixing for the el-GR locale, if there is anything more, let me know!

2024-04-02 16:00 UTC, andrey-helldar commented
@michaelkonstantinou, I sent an invite to the post office.

Useful information:

- Our repositories: https://github.com/orgs/Laravel-Lang/repositories
- Our website: https://laravel-lang.com
- If you want, there is even a chat room in Telegram (It was created recently, so there's no one in it but us, yet 😅): https://t.me/addlist/l0XGtvEIBiljMTMy
- Translation statuses: https://laravel-lang.com/statuses.html
- Team List: https://github.com/orgs/Laravel-Lang/people, https://laravel-lang.com/our-team.html

And welcome to the @Laravel-Lang/laravel-lang team! 🥳

2024-04-03 07:16 UTC, Van4kk commented
@michaelkonstantinou, Welcome to the team 🤗