[pt: ] Updated PT-PT translations
Laravel-Lang/lang pull request #4911
Opened 2024-09-08 00:07 UTC by helderneves91

2024-09-08 00:10 UTC, andrey-helldar commented
@jorgercosta, can you check this PR?

2024-09-24 11:00 UTC, andrey-helldar requested changes

2024-09-24 11:00 UTC, andrey-helldar commented on locales/pt/json.json
> -    "Honduras": "Honduras",
Keys do not need to be deleted. When translations match, they are simply specified in the "excludes" file.

2024-09-24 11:00 UTC, andrey-helldar commented on locales/pt/json.json
> -    "Hong Kong": "Hong Kong",
Keys do not need to be deleted. When translations match, they are simply specified in the "excludes" file.

2024-09-24 11:00 UTC, andrey-helldar commented on locales/pt/json.json
> -    "Uganda": "Uganda",
Keys do not need to be deleted. When translations match, they are simply specified in the "excludes" file.

2024-09-30 10:47 UTC, andrey-helldar commented
@helderneves91, can you fix that?

2024-09-30 13:48 UTC, helderneves91 commented
> @helderneves91, can you fix that?

Hi, sure, I'll handle this tonight

2024-09-30 16:05 UTC, andrey-helldar commented
@jorgercosta is probably pretty busy, so I'll be able to accept this PR without checking it as soon as the test issues are fixed.

2024-10-01 09:00 UTC, helderneves91 commented
Hi @andrey-helldar , please validate the changes.

2024-10-01 09:23 UTC, andrey-helldar requested changes

2024-10-01 09:23 UTC, andrey-helldar commented on locales/pt/json.json
> -    "Costa Rica": "Costa Rica",
We need to get that key back

2024-10-01 10:00 UTC, andrey-helldar approved these changes
Obrigado!

2024-10-01 10:00 UTC, merged

2024-10-01 10:20 UTC, helderneves91 commented
I'm sorry but the mess, I didn't realized that we don't need to remove the excluded keys from the files. Won't happen again in the next PR's.

2024-10-01 10:38 UTC, andrey-helldar commented
It's ok 👍