Translation fix
Laravel-Lang/lang pull request #4930
Opened 2024-10-31 20:18 UTC by amdad121

Some of translation bug fix.

2024-10-31 21:14 UTC, arman-arif requested changes
Please update the translation, with the correct sentence.

2024-10-31 21:14 UTC, arman-arif commented on locales/bn/php.json
> +    "min.string": ":Attribute অবশ্যই :min অক্ষর এর চেয়ে ছোট হতে পারবে না।।",
Same problem here.
 "The :attribute must be at least :min characters."

2024-10-31 21:14 UTC, arman-arif commented on locales/bn/php.json
> +    "min_digits": "এই :attribute এ সর্বোনিম্ন :min ডিজিট হতে পারবে না।।",
Same problem here.
"The :attribute field must have at least :min digits."

2024-11-01 09:08 UTC, amdad121 commented
> Please update the translation, with the correct sentence.

Thank you. I have updated.

2024-11-01 09:44 UTC, arman-arif approved these changes

2024-11-01 09:45 UTC, arman-arif commented
Thank you, It looks fine now.

2024-11-01 09:45 UTC, merged

2024-11-01 10:30 UTC, andrey-helldar commented
@amdad121, @arman-arif, তোমাকে ধন্যবাদ

Released: https://github.com/Laravel-Lang/lang/releases/tag/15.9.0